name: Java CI with integration and UI tests

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: school
    strategy:
      matrix:
        # test against several Java versions
        include:
          - java: 8
          - java: 11
          
    name: Build with Java ${{matrix.java}} on Linux
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v1
      with:
       java-version: ${{matrix.java}}
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
       path: ~/.m2
       key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
       restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven
      run: xvfb-run mvn verify
      working-directory: ${{env.workdir}}
      