name: Java CI with integration, e2e tests and SonarCloud

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: school
                
    name: Build with Java 11 on Linux
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
       java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
       path: |
         ~/.m2
         ~/.sonar/cache
       key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yml')}}
       restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run mvn verify -Pjacoco sonar:sonar
        -Dsonar.organization=LorenzoCorbinelli-github
        -Dsonar.host.url=https://sonarcloud.io
      working-directory: ${{env.workdir}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}